---
title: "262 HW 4"
author: "Molly Williams and Mario Colon"
date: "5/31/2019"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(reshape2)
```

### Background

Create a function that calculates the following:

- most frequently caught fish in each location
- total revenue for each location
- total fisheries revenue sum
- produces graph of revenue by location and total revenue (as text) when user requests 


### Load data tables for fish prices and catch by location
```{r}

fish_catch <- read_csv("fish_catch.csv")
fish_prices <- read_csv("fish_prices.csv")

# Created these in excel using made-up numbers, saved as csvs 
# Catch is in pounds, price is in $ USD per pound


```


### Create function 

```{r}

# Source the R file that contains function auto() and includes all of the pre-set parameters for calculating vehicle power
source("fish_function.R")


```

### Run function 

```{r}

graph_output <- calc_fish_revenue(l = fish_catch, p = fish_prices, graph_result = TRUE)

graph_output

no_graph_output <- calc_fish_revenue(l = fish_catch, p = fish_prices, graph_result = FALSE)

no_graph_output

```


